version: '3.8'

services:
  app:
    build: .
    container_name: devops-notes-app
    ports:
      - "8084:80"

  redis:
    image: redis
    container_name: devops-redis
    ports:
      - "6379:6379"