apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  APP_VERSION: "1.3.0"
  APP_ENVIRONMENT: "kubernetes"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  GUNICORN_WORKERS: "2"
  GUNICORN_THREADS: "4"
  GUNICORN_TIMEOUT: "30"
  GUNICORN_GRACEFUL_TIMEOUT: "30"
